### ISSUE TITLE
Perl Script on OSX downloads SourceForge's HTML download page instead of the files

### ISSUE THREAD

**Issue by AgentEpsilon** [devkitPro/installer#1]
Each file that is downloaded gives me the following result for the `file` command:

```
gp32-examples-20051021.tar.bz2: HTML document text
```

It looks like this has to do with trying to download the files off of SourceForge. Even though it looks like `curl` does have callbacks enabled (with a `-L` flag), it is not downloading the files. I attempted to download them myself using [these instructions](https://sourceforge.net/blog/download-ninja/), but they do not appear to work with `curl -L` _or_ `wget`.

Any ideas would be appreciated - I am definitely willing to help.

**Comment by WinterMute** [comment]
What does the html say? Usually it's an error message relating to some Sourceforge problem & the issue gets fixed later.

**Comment by AgentEpsilon** [comment]
It looks like its the SourceForge download page: [Gist](https://gist.github.com/AgentEpsilon/3afb789f04b1cb9bfba8)
So it may be a problem with curl not loading the page fully & waiting for the file to download.
