### ISSUE TITLE
devkitPro Updater v3.0.3 not downloading any file (Windows 7)

### ISSUE THREAD

**Issue by tigrouind** [devkitPro/installer#11]
If  I run the installer (with administrator rights) and check "Minimal System" + "NDS Development" nothing is downloaded. Only following files/folders are created in "C:\devkitPro": 

> devkitPro.url
> devkitProUpdater-3.0.3.exe
> installed.ini
> msys2
> uninst.exe

mysys2 folder is empty. 
There is no nds libraries and such

**Comment by tigrouind** [comment]
I finally found the error. It seems the installer use IE to download the files and there is something wrong with SSL certificates.

To fix this, I typed "inetcpl.cpl". Then went to "Advanced" tab and checked all SSL related checkboxes at the bottom of the list (only a few are checked by default). After downloading devkitpro I reset them to default as it might cause security issues.

**Comment by WinterMute** [comment]
Hmm, that's interesting. The downloader plugin uses the IE proxy settings to access the internet but it usually errors if it can't connect.

I'll have a look and see if I can replicate this on a VM.

**Comment by tigrouind** [comment]
Sometimes there is no error at all. From the log in installer you can see it's running msys commands but nothing happen (which it's probably because msys hasn't been downloaded at all). I got "success" installation message. It only install files I reported in the OP.
Sometimes I got the following error message (I think it happen if I try to re-run installer from c:\devkitpro after failed installation) : 

> your internet connection seems to be not permitted or dropped out

It's not related to firewall or antivirus (which I tried to disable).
I got the following errors reported in windows event viewer  : 

> schannel -EventID 36887 - fatal alert 40
> schannel -EventID 36887 - fatal alert 70

That is how I found out it was related to SSL

**Comment by kevlarballoons** [comment]
This happens to me as well, and the SSL fix worked

**Comment by tiliarou** [comment]
The installer doesn't support authenticated HTTP/S proxy. Although IE accesses the internet properly, the installer (and pacman) aren't able to access the net. I had to use Proxifier to specify directly and forcefully the proxy username and password.

**Comment by Cration** [comment]
> I finally found the issue. It seems the installer use IE to download the files (i am not sure about this) and there is something wrong with SSL certificates.
> 
> To fix this, I did the following :
> 
> > run "inetcpl.cpl"
> > go to "Advanced" tab
> > check all SSL related checkboxes at the bottom of the list (only a few are checked by default).
> 
> After I did that, the installer downloaded all appropriate files and it went fine.

In Windows 10, also check the "use TSL x.x". Works for me.

**Comment by raxoft** [comment]
I can confirm that in Windows 7, just checking "use TLS 1.1" and "use TLS 1.2" as per the advice given above was enough to fix the downloading issue. Thanks for the tip!

**Comment by ccfman2004** [comment]
That didn't fix my issue with downloading files in Windows 10 2004.

**Comment by WinterMute** [comment]
> That didn't fix my issue with downloading files in Windows 10 2004.

This issue describes problems with Windows 7. Please open a new issue and describle your problem in full.

**Comment by ccfman2004** [comment]
I figured out the issue.  My ISP (Comcast) was blocking access to the site needed to download the files from.  Using a VPN solved the issue.

**Comment by Cryosignal** [comment]
Also had an issue with Comcast! Your post came in at the perfect time to help me, thank you!

**Comment by ccfman2004** [comment]
For some reason Comcast is listing the downloads domain as Malware.

**Comment by WinterMute** [comment]
This issue is about SSL support in IE. Please report Comcast issues to Comcast. We have no control over their Xfinity Security filter.

**Comment by splapoon** [comment]
if this issue is revolved, close it,

**Comment by pyanmcbride** [comment]
Help. The same thing is happening to me. I tried everything above and it still will not work.
