### ISSUE TITLE
Msys2 home folder default 

### ISSUE THREAD

**Issue by LBS71** [devkitPro/installer#12]
After installing devkitpro v3.0.3 on a windows 10 64bits fresh install ,

when launching msys2 the home directory point on the windows users folder instead of the home folder in the MSYS folder.

**Comment by fincs** [comment]
This is the intended behaviour. What's the problem?

Also please note: [devkitPro is the organisation that provides the tools. We are not a software package and we don't have version numbers)](https://devkitpro.org/wiki/Getting_Started). The version number you pointed out refers to our installer program, devkitProUpdater.

**Comment by LBS71** [comment]
since when ? 
when i was in version 2 , my msys2 home would be in the devkitpro folder , and now it be in the c:\Users folder   :-(

How can i do to be by default in my devkitpro msys home folder ?

**Comment by fincs** [comment]
Why do you want it to be a folder that doesn't contain anything? For consistency's sake with other operating systems, it is routed to the actual Windows equivalent of "/home".

**Comment by LBS71** [comment]
damage it was more convenient before :-(

**Comment by fincs** [comment]
I would say it's more convenient now, since you don't have to hunt down looking for a random folder hidden beneath the directory structure.

**Comment by fincs** [comment]
> devkitARM's msys2 isn't the only msys installation on my PC

If you already had a msys2 installation, you don't need this installer. You can directly [add devkitPro repositories](https://devkitpro.org/wiki/devkitPro_pacman) to your existing msys2 setup.

**Comment by geckojsc** [comment]
Oh thanks, that's good to know :)
