### ISSUE TITLE
Environmental Variables set to Linux/Mac locations on install

### ISSUE THREAD

**Issue by purposelycryptic** [devkitPro/installer#17]

**Comment by WinterMute** [comment]
They's not set to linux/mac locations. msys2 provides that /opt/devkitpro mount point & the msys tools understand it.

**Comment by purposelycryptic** [comment]
> They's not set to linux/mac locations. msys2 provides that /opt/devkitpro mount point & the msys tools understand it.

Well after install I had to manually change them to their actual locations, so... I don't know what to tell you except it doesn't seem to work as is.

**Comment by WinterMute** [comment]
Probably better off hitting us up on IRC. This stuff can be hard to figure out in issue trackers - see https://devkitpro.org/wiki/Community_Portal
