### ISSUE TITLE
Need of 32bit versions

### ISSUE THREAD

**Issue by Halfshadow** [devkitPro/installer#18]
Please don't judge me but I'm poor and I can't change my notebook, and install a 64 bit OS.

Can I have an older version that could works like the 3.0.3 version to works with NSMBe5.exe and ASMPatchTemplate-master to simply apply the .s patches to try ASM experiments please?

**Comment by Cyuubi** [comment]
If your running Linux, you can try to use QEMU user-mode emulation to run X64 binaries, but be warned, this is very slow and definitely not recommended.

**Comment by Cyuubi** [comment]
You know, editing OPs post to remove an old version isn't going to help your case (GitHub shows edited post history), I was trying to give the best help I could (so that he didn't need to use an old version) yet your censoring me from trying to provide help.

**Comment by WinterMute** [comment]
- Please don't link unofficial binaries on our issue tracker. We have no idea what they are or where they came from and advise against using them.
- People offering ludicrous advice on these trackers will be blocked.

If you already have a 32bit setup from when the installer was 32bit then please uninstall it first, making sure that you back up anything inside the devkitpro folder you wish to keep. (Please note, you should not have put anything in there in the first place, we've always advised users not to)

Currently the easiest way to get set up with 32 bit binaries on windows is to install the 32bit msys2 from https://www.msys2.org/ (that's the msys2-i686 installer, not the x86_64 one. You'll then need to add the devkitPro repos to pacman, see https://devkitpro.org/wiki/devkitPro_pacman#Customising_Existing_Pacman_Install for details. 

Please don't instruct other people to do this or copy these instructions anywhere else. We do hope to sort out a new installer soon.

**Comment by Halfshadow** [comment]
> * Please don't link unofficial binaries on our issue tracker. We have no idea what they are or where they came from and advise against using them.
> * People offering ludicrous advice on these trackers will be blocked.
> 
> If you already have a 32bit setup from when the installer was 32bit then please uninstall it first, making sure that you back up anything inside the devkitpro folder you wish to keep. (Please note, you should not have put anything in there in the first place, we've always advised users not to)
> 
> Currently the easiest way to get set up with 32 bit binaries on windows is to install the 32bit msys2 from https://www.msys2.org/ (that's the msys2-i686 installer, not the x86_64 one. You'll then need to add the devkitPro repos to pacman, see https://devkitpro.org/wiki/devkitPro_pacman#Customising_Existing_Pacman_Install for details.
> 
> Please don't instruct other people to do this or copy these instructions anywhere else. We do hope to sort out a new installer soon.

Ok, I'll try soon thank you. I hope will works with the tool I want to use. I need of use it with NSMBe5.exe. Will works I hope. :)

**Comment by Halfshadow** [comment]
> * Please don't link unofficial binaries on our issue tracker. We have no idea what they are or where they came from and advise against using them.
> * People offering ludicrous advice on these trackers will be blocked.
> 
> If you already have a 32bit setup from when the installer was 32bit then please uninstall it first, making sure that you back up anything inside the devkitpro folder you wish to keep. (Please note, you should not have put anything in there in the first place, we've always advised users not to)
> 
> Currently the easiest way to get set up with 32 bit binaries on windows is to install the 32bit msys2 from https://www.msys2.org/ (that's the msys2-i686 installer, not the x86_64 one. You'll then need to add the devkitPro repos to pacman, see https://devkitpro.org/wiki/devkitPro_pacman#Customising_Existing_Pacman_Install for details.
> 
> Please don't instruct other people to do this or copy these instructions anywhere else. We do hope to sort out a new installer soon.

I can't download the second installer on evkitpro.org, tell me "forbidden" if I click to the 32 bit link.

**Comment by WinterMute** [comment]
> I can't download the second installer on devkitpro.org, tell me "forbidden" if I click to the 32 bit link.

No, download the i686 msys2 installer from https://www.msys2.org and install that. Then follow the instructions on the devkitpro wiki page to add our repositories to the msys2 pacman. It might be easier to help you in real time, can you get on IRC or some other chat medium?

**Comment by Halfshadow** [comment]
I'm now on Discord, Half#3193

**Comment by coolboi1234** [comment]
wintermute is a sjw asshole.

**Comment by coolboi1234** [comment]
kys wintermute

**Comment by WinterMute** [comment]
Closing due to no further contact.
