### ISSUE TITLE
error: GPGME error: No data

### ISSUE THREAD

**Issue by TheBlueOompaLoompa** [devkitPro/installer#22]
When I run the installer it runs into the error "error: GPGME error: No data" and when I run the command "pacman -Sl" in msys2 that devkitpro installs it gives the same error
![image](https://user-images.githubusercontent.com/53215039/78159605-628a1b80-7408-11ea-8380-516aa111eb0d.png)

I also did a bit of digging and I found that the servers for installing these packages are down, any eta on when they might be up again.

**Comment by WinterMute** [comment]
The servers aren't down.

From your msys shell run the command `cat /opt/devkitpro/pacman/var/lib/pacman/sync/dkp-libs.db` and paste the output here. You should be able to highlight the text in the window & right click copy in the context menu. Failing that ``cat /opt/devkitpro/pacman/var/lib/pacman/sync/dkp-libs.db > test.txt` then open that test.txt file in a text editor & copy & paste from there.

**Comment by TheBlueOompaLoompa** [comment]
cat: /opt/devkitpro/pacman/var/lib/pacman/sync/dkp-libs.db: No such file or directory
The opt directory is empty when I looked in there.

**Comment by WinterMute** [comment]
What's the output of `ls -al /opt/`?

**Comment by TheBlueOompaLoompa** [comment]
total 8
drwxr-xr-x 1 ben ben 0 Feb 18  2018 .
drwxr-xr-x 1 ben ben 0 Apr  1 14:18 ..
drwxr-xr-x 1 ben ben 0 Apr  1 14:20 devkitpro

**Comment by WinterMute** [comment]
As above, use `cat /var/lib/pacman/sync/dkp-libs.db`

**Comment by TheBlueOompaLoompa** [comment]
<!doctype html>
<html lang="en">

<head>
  <meta name="referrer" content="unsafe-url">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Potential Threat Detected</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="msapplication-TileColor" content="#000000">
  <meta name="msapplication-config" content="./browserconfig.xml">
  <meta name="theme-color" content="#000000">

  <link rel="stylesheet" href="./css/theme-xdns-security.min.css" inline>

  <script type="text/javascript" src="js/jquery/jquery.js"></script>
  <script type="text/javascript" src="js/class/class.min.js"></script>
  <script type="text/javascript" src="js/jquery-encoder/jquery.jquery-encoder.min.js"></script>
  <script type="text/javascript" src="js/warn.js"></script>
</head>

<body onload="render()">
  <header class="header">
    <img src="./img/icon_enhanced-security-no-threats.svg" height="70" alt="" inline>
  </header>
  <div class="wrapper">
    <h1>Hold On!</h1>
    <hr noshade>
    <div class="section_info">
      <p>We blocked access to</p>
      <p id="site"></p>
    </div>
    <div class="subheader">
      <p>This site might compromise your device or contain dangerous content. <br/>
To avoid these risks, close this window and skip this site. </p>
    </div>
    <div class="buttons">
      <a href="#" class="access_link" id="unsafe" rel="noopener noreferrer">Proceed Anyway</a>
    </div>
  </div>
</body>

</html>

I looked at the html and it detects what was returned from the servers as a threat.

**Comment by WinterMute** [comment]
It doesn't detect anything as a threat. Your ISP is using a filter service that blocks devkitPro urls, I don't know why. Can you check if you can get to https://devkitpro.org & let me know if that works or has the same message.

What ISP are you using? Can you disable protected browsing? Does https://www.xfinity.com/support/articles/xfinity-xfi-faqs#protect help any?

**Comment by TheBlueOompaLoompa** [comment]
I can get to [https://devkitpro.org ](url) and I am using xfinity but I am not the admin, I did send a message to temporarily turn it off so I can attempt to install the required files with that.

**Comment by TheBlueOompaLoompa** [comment]
Yes, you were right I had the idea of doing a wifi hotspot from my phone instead and immediately when I tried reinstalling all the packages worked thank you so much, this thing has been a pain for the past month or two.

**Comment by TheBlueOompaLoompa** [comment]
Waiting to close this until I have it compiling the hello world stuff just to make sure everything is there.

**Comment by TheBlueOompaLoompa** [comment]
It compiled successfully and ran under dolphin perfectly!

**Comment by WinterMute** [comment]
One last thing, when you said you found that the servers for installing these packages are down what did you mean? How did you test that?

Can you try http://downloads.devkitpro.org/packages via your Xfinity connection & see if that gives the unsafe message or is it just http://downloads.devkitpro.org/packages/dkp-libs.db ?

**Comment by TheBlueOompaLoompa** [comment]
Yeah it says that link is unsafe
![image](https://user-images.githubusercontent.com/53215039/78200802-5a0c0200-7455-11ea-8c3e-1d6e61f2092c.png)
