### ISSUE TITLE
Need a 32 bit compatible

### ISSUE THREAD

**Issue by TaielF** [devkitPro/installer#23]
Well, just that. I wanna know if u guys have a devkitpro compatible with 32 bits.

Sorry for my bad english btw.

Thanks!

**Comment by WinterMute** [comment]
What system are you looking for? Is there no possibility of upgrading to 64bit? Many projects are dropping 32 bit support now, including msys2 which we depend on for unix tools.

**Comment by WinterMute** [comment]
Closing due to lack of further information.
