### ISSUE TITLE
Unable to install packages

### ISSUE THREAD

**Issue by lioncash** [devkitPro/installer#26]
Hi,

I've recently reinstalled devkitPro on a new Windows environment and I seem to keep getting errors like following:

![Untitled](https://user-images.githubusercontent.com/712067/88448177-cc3f9280-ce08-11ea-8d6e-88b6abc1f6c9.png)

I've tried uninstalling and then reinstalling devkitPro using the graphical installer, but this also occurs during the installation process when the installer attempts to pull packages from the server.

I tried accessing [https://downloads.devkitpro.org/packages/](https://downloads.devkitpro.org/packages/) to see if it was a network issue on my end, and that doesn't seem to be the case.

Sorry for the issue, but is there anything that can be thought of to resolve this? I've never had this happen to me before, so I don't know how I'd address this myself.

**Comment by WinterMute** [comment]
msys2 have some new packagers so there's a bit of a dance to do in order to get a new keyring. See https://www.msys2.org/news/#2020-06-29-new-packagers for details.

I'll need to update our msys2 tarball so new installations don't error. Hopefully get to it soon. Only just found out about this myself yesterday.

**Comment by lioncash** [comment]
Thanks for the response! This worked for me and I'm able to retrieve some packages now. Some, however, seem to fail to download with a 500 error code.

![Untitled](https://user-images.githubusercontent.com/712067/88469282-ef784980-cebd-11ea-9a34-dfd7f9046e35.png)

Still closing the issue though, since the downloading issue itself is fixed.

**Comment by thejsa** [comment]
@lioncash Re; 500 errors, there was a server configuration issue which should now be fixed; could you try again?

**Comment by lioncash** [comment]
Server issue seems to be resolved now and everything downloads. Thanks again :)
