### ISSUE TITLE
Windows graphical installer not download the required files

### ISSUE THREAD

**Issue by 64801965** [devkitPro/installer#27]
Only downloaded msys2 dir but nothing including PPC and ARM files. Seems it prompted keys are unknown...
Using Win10.

**Comment by NicholasMoser** [comment]
I'm seeing something similar to this. I select all components to install:

![image](https://user-images.githubusercontent.com/4983605/88741668-e11c6e80-d105-11ea-8244-b3d32e64e6eb.png)

Partway through I see these errors:

![image](https://user-images.githubusercontent.com/4983605/88741693-f2657b00-d105-11ea-8972-e62d7875b2f5.png)

![image](https://user-images.githubusercontent.com/4983605/88741769-1e80fc00-d106-11ea-9244-adaa4d1cb0c3.png)

And then I repeatedly see:

![image](https://user-images.githubusercontent.com/4983605/88741795-3193cc00-d106-11ea-8786-0042d41399ff.png)

Despite this, it thinks it has installed correctly:

![image](https://user-images.githubusercontent.com/4983605/88741866-525c2180-d106-11ea-8614-7bd347533a8c.png)

When I actually run it, there's no PPC files:
```
$ echo $DEVKITPPC
/opt/devkitpro/devkitPPC
$ cd $DEVKITPPC
-bash: cd: /opt/devkitpro/devkitPPC: No such file or directory
```

Looking into a few different solutions, I'll update this issue if I discover anything on my end :)

**Comment by fincs** [comment]
We're aware of this issue (as well as what causes it). Please bear with us, as we're working on a solution.

**Comment by WinterMute** [comment]
If the uninstaller exists (uninst.exe in the devkitpro folder) then run it and remove the partial install. If the uninstaller hasn't been written to disk then just remove the whole folder manually and reboot. Make sure you also remove msys-2.10.0.7z from your system to ensure the updater downloads the most recent version then run the updater again. Everything should hopefully just work.

@NicholasMoser  
> Looking into a few different solutions, I'll update this issue if I discover anything on my end :)

Please don't share solutions and workarounds you discover without first checking with us that they're appropriate. That pretty much always causes further support headaches for us. Thanks for reporting the issue here rather than attempting to research a workaround and implement your own solution first though. That's very much appreciated.

FWIW you don't need to censor the gpg public key fingerprints displayed by the installer. If they were secrets that shouldn't be revealed then the damage would already have been done :P

**Comment by NicholasMoser** [comment]
I can confirm that it is now fixed and working properly. Thank you for such quick turn around! I made a donation to show my appreciation 😃

**Comment by WinterMute** [comment]
Awesome, good to hear.

**Comment by 64801965** [comment]
No, the same as before now, folks!

**Comment by 64801965** [comment]
![无标题](https://user-images.githubusercontent.com/44165521/89730455-4874df80-da71-11ea-8193-99c3ab3309e0.png)

**Comment by WinterMute** [comment]
@64801965

Try this.

If the uninstaller exists (uninst.exe in the devkitpro folder) then run it and remove the partial install. If the uninstaller hasn't been written to disk then just remove the whole folder manually and reboot. Make sure you also remove msys-2.10.0.7z from your system. Also try clearing IE cache - press windows key + R & type inetcpl.cpl. Under Browsing History click delete. In the following dialog make sure you have "Temporary Internet files and website files" and "Cookies and webiste data" ticked then click delete again.

![image](https://user-images.githubusercontent.com/101194/89734993-3c7c2400-da57-11ea-87df-8a219f10e3ba.png)

**Comment by 64801965** [comment]
> 
> 
> @64801965
> 
> Try this.
> 
> If the uninstaller exists (uninst.exe in the devkitpro folder) then run it and remove the partial install. If the uninstaller hasn't been written to disk then just remove the whole folder manually and reboot. Make sure you also remove msys-2.10.0.7z from your system. Also try clearing IE cache - press windows key + R & type inetcpl.cpl. Under Browsing History click delete. In the following dialog make sure you have "Temporary Internet files and website files" and "Cookies and webiste data" ticked then click delete again.
> 
> ![image](https://user-images.githubusercontent.com/101194/89734993-3c7c2400-da57-11ea-87df-8a219f10e3ba.png)

Nothing helped...
![无标题](https://user-images.githubusercontent.com/44165521/89755735-0603df00-db13-11ea-87d9-386945aa0626.png)

**Comment by NicholasMoser** [comment]
@64801965 

>Make sure you also remove msys-2.10.0.7z from your system 

Did you make sure to delete this file before rerunning the install exe?

**Comment by WinterMute** [comment]
@64801965
> 
> > Make sure you also remove msys-2.10.0.7z from your system
> 
> Did you make sure to delete this file before rerunning the install exe?

This. Make absolutely sure that msys2-2.10.0.7z is not still present before running the installer again. Make sure the devkitPro folder on your install drive has been removed.

**Comment by 64801965** [comment]
Yeah, done that, everything remained--lack of some files downloaded.

**Comment by WinterMute** [comment]
@64801965 
> Yeah, done that, everything remained--lack of some files downloaded.

OK, let's try something else.

Delete everything inside your devkitPro folder **except** devkitProUpdater-3.0.3.exe
Right click this link and select "Save As" https://pkg.devkitpro.org/msys-2.10.0.7z
Browse to your devkitPro folder & save the file there.
Now run devkitProUpdater-3.0.3.exe again.

**Comment by 64801965** [comment]
Good news... Evething works! Thank you!
> 
> @64801965
> 
> > Yeah, done that, everything remained--lack of some files downloaded.
> 
> OK, let's try something else.
> 
> Delete everything inside your devkitPro folder **except** devkitProUpdater-3.0.3.exe
> Right click this link and select "Save Link As" https://pkg.devkitpro.org/msys-2.10.0.7z
> Browse to your devkitPro folder & save the file there.
> Now run devkitProUpdater-3.0.3.exe again.
