### ISSUE TITLE
devkitPro Updater v3.0.3 not downloading anything other than msys2 (Windows 8.1)

### ISSUE THREAD

**Issue by thiaguinhohp** [devkitPro/installer#29]
I'm in Windows 8.1 and when I used the 3.0.3 installer couldn't download anything other than msys2. I tried the SSL solution in the issue above but the problem persisted.

However when i used the 3.0.2 installer everything went fine.

**Comment by WinterMute** [comment]
There's no difference between the 3.0.2 and 3.0.3 installers that would explain this other than simple coincidence. Chances are you accidentally cancelled something or there was a temporary issue with a server connection.
