### ISSUE TITLE
URL's may not be valid anymore

### ISSUE THREAD

**Issue by mclayan** [devkitPro/installer#3]
When manually trying to open the link to the update file on Sourceforge (http://devkitpro.sourceforge.net/devkitProUpdate.ini) in a browser, the following message will be displayed by the website: "Project web is currently offline pending the final migration of its data to our new datacenter."

**Comment by c-schuhmann** [comment]
Seems to be solved since d79ec76baab997a5c2f9975f9eb6b451544a7583

**Comment by WinterMute** [comment]
Sourceforge finally got project web back up just in time for the installers to move everything to github
