### ISSUE TITLE
Is this the full installer

### ISSUE THREAD

**Issue by JoeyDevmarco** [devkitPro/installer#30]
the download page says instaler but here it says updater. where can I get installer?

**Comment by splapoon** [comment]
it does both

**Comment by JoeyDevmarco** [comment]
I still don’t have an answer yet this is closed

**Comment by WinterMute** [comment]
> I still don’t have an answer yet this is closed

Sorry, must've hit close instead of "comment & close"

It's called the updater because it both installs and updates.
