### ISSUE TITLE
problem on installing the Devkit

### ISSUE THREAD

**Issue by ZarxielZerg** [devkitPro/installer#31]
I'm having problem on installing it, and not know why...
even after upload it with the installer I don't get the "devkitARM" that for what they told to me is necessary.

here some screenshots.

https://media.discordapp.net/attachments/200749908368687104/789812291373498418/unknown.png?width=841&height=473

https://cdn.discordapp.com/attachments/200749908368687104/789813194678992906/unknown.png

I don't know what I should do

**Comment by Micba-bars** [comment]
Have you figured this out? I have the same problem, but can't find a solution.

**Comment by WinterMute** [comment]
This occasionally happens when keys get updated in upstream msys2 and we haven't updated our base bundle to match. It should currently be working.
