### ISSUE TITLE
semaphore.h missing

### ISSUE THREAD

**Issue by clamtram** [devkitPro/installer#33]
Hi,

I'm a bit of a noob at this, but I have recently tried to run "make" on a software called "netslug" (an online local co-op emulator for wii Super MArio Bros). I am getting an error saying "ogc/semaphore.h: No such file or directory" as per below. I assume this is an issue with devkitPro, as the code would be using devkitPro to perform "make"? Others have had success with the "netslug" software but it was a few years ago so they could have used a different version? 

Any help would be very much appreciated.

Cheers!

![106350022-b2c65880-630d-11eb-92ae-307c1d508e69](https://user-images.githubusercontent.com/62830226/106380382-ce546080-63ec-11eb-9a32-499d2c73170a.jpg)

**Comment by clamtram** [comment]
Think I found the issue, older scripts need the previous versions of Devkitpro to execute. See link below. 

https://gbatemp.net/threads/collection-of-old-devkitpro-versions.526377/

Also note that the particular script i was trying to compile can be found online here:

https://gbatemp.net/threads/netslug-for-wii-finally-compiled-download-link.483064/

**Comment by WinterMute** [comment]
devkitPro is a provider of tools and libraries not a software package.

This is most likely an issue with whatever you're trying to compile and not our tools unless of course youve somehow managed to not install libogc.

Upstream of this fork has been more recently updated than this. See https://github.com/Chadderz121/brainslug-wii

I'll have a look at correcting the Makefile there.

**Comment by clamtram** [comment]
Thanks mate, much appreciated
