### ISSUE TITLE
make: *** [Makefile:102: build] Error 2

### ISSUE THREAD

**Issue by Edx09** [devkitPro/installer#37]
This is what it says in the console (cmd + programmer´s notepad)

> linking ... template.elf
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/devkitPro/libogc/lib/wii\libogc.a(system.o): in function `__init_syscall_array':
/media/harddisk1/libogc/libogc/system.c:296: undefined reference to `__syscalls'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: /media/harddisk1/libogc/libogc/system.c:296: undefined reference to `__syscalls'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: /media/harddisk1/libogc/libogc/system.c:296: undefined reference to `__syscalls'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/devkitPro/libogc/lib/wii\libogc.a(ipc.o): in function `__ios_ioctlvformat_parse':
/media/harddisk1/libogc/libogc/ipc.c:487: undefined reference to `__ctype_ptr__'
/media/harddisk1/libogc/libogc/ipc.c:487:(.text.__ios_ioctlvformat_parse+0xfc): unresolvable R_PPC_EMB_SDA21 relocation against symbol `__ctype_ptr__'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld.exe: /media/harddisk1/libogc/libogc/ipc.c:589: undefined reference to `__ctype_ptr__'
/media/harddisk1/libogc/libogc/ipc.c:589:(.text.__ios_ioctlvformat_parse+0x4ac): unresolvable R_PPC_EMB_SDA21 relocation against symbol `__ctype_ptr__'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/devkitPPC/wii_rules:30: /d/Projects/template/template.elf] Error 1
make: *** [Makefile:102: build] Error 2

**Comment by WinterMute** [comment]
reinstall your toolchain by running `pacman -S wii-dev` from an msys terminal. You'll find a shortcut in the start menu under devkitPro.

Please don't modify your toolchain installation with random binaries from elsewhere. If you need help compiling something with latest tools then please ask in forums at https://devkitpro.org
