### ISSUE TITLE
After using the installer a program appears on the Aplications list of Windows 10 and does not uninstalls

### ISSUE THREAD

**Issue by TheHENOOB** [devkitPro/installer#39]
![image](https://user-images.githubusercontent.com/74883505/119421890-1cf87400-bcd6-11eb-8661-2a9560e3feb3.png)
After i downloaded a file on the program this appeared and i tried a lots of ways to remove it, i deleted the original installer, i used regedit.exe and nothing helped, there's a way of retiring this on the list?

**Comment by WinterMute** [comment]
I don't really understand your issue here. You used the updater to install toolchains & then deleted it but you expect the Programs and Features entry to be removed without running the uninstaller?

**Comment by TheHENOOB** [comment]
The program failed to install in the first time (so it didn't come with the uninstaller and it got registered on the list of applications), i just downloaded only the gba package and then the software appeared on the list of applications, i will close this issue because after time i found the key value of the app, then i deleted and the program does not appear on the list anymore
