### ISSUE TITLE
Installer not wanting to install

### ISSUE THREAD

**Issue by keatsoo** [devkitPro/installer#42]
Hello,
I'm trying to install the toolkit, but it gets stuck at msys and the download rate drops (i normally have 300mb/s in download, but the installer was downloading at 0.5kb/s even though there isnt anything else connected to my wifi??????????). I'm on Windows 10 and tried everytging but nothing worked.
Can someone help please ?
Thank you

**Comment by WinterMute** [comment]
Close the installer. Type "command prompt" into the search box on your taskbar. Select "Run as administrator" then, in the cmd window that opens type `ipconfig /flushdns`. Open the installer and try again.

![image](https://user-images.githubusercontent.com/101194/152198682-fd920058-7fa7-4c66-a9dd-91c472b20615.png)

**Comment by keatsoo** [comment]
> Close the installer. Type "command prompt" into the search box on your taskbar. Select "Run as administrator" then, in the cmd window that opens type `ipconfig /flushdns`. Open the installer and try again.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/101194/152198682-fd920058-7fa7-4c66-a9dd-91c472b20615.png)
> 
> 

It still doesn't work :/
The new thing though is that after 1min of downloading msys, i got the "your internet dropped out" message

**Comment by WinterMute** [comment]
OK. This time type `inetcpl.cpl` in that same box & click open. Then click on the advanced tab and scroll down the list until you see the ssl options under Security. Tick `Use TLS 1.1` and `Use TLS 1.2`

![image](https://user-images.githubusercontent.com/101194/152204026-8b3bf6e0-e3d6-4ad8-8917-73e0116ab0a8.png)

**Comment by keatsoo** [comment]
> OK. This time type `inetcpl.cpl` in that same box & click open. Then click on the advanced tab and scroll down the list until you see the ssl options under Security. Tick `Use TLS 1.1` and `Use TLS 1.2`
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/101194/152204026-8b3bf6e0-e3d6-4ad8-8917-73e0116ab0a8.png)
> 
> 

It still doesn't work :/

**Comment by Baune8D** [comment]
Same issue here. Downloading with 0.8 kb/s and it regularly says `your internet dropped out`

**Comment by tevey** [comment]
Same issue for me

**Comment by WinterMute** [comment]
OK. Everybody retry now.

**Comment by Baune8D** [comment]
No improvements for me here, still downloading with less than 1kB/s. It starts off a little higher but then drops on speed fast and after a little while stalls completely.

I seem to be able to get better speed by downloading the file directly from `http://downloads.devkitpro.org/msys-2.10.0.1.7z` through Free Download Manager, it gives me around 50kB/s - 100kB/s for 20 seconds, but then completely stalls, i can then pause and unpause it to get speed again for around 20 seconds.

**Comment by ijacquez** [comment]
I'm also having the same issue.

**Comment by WinterMute** [comment]
Hopefully it should be sorted now.

**Comment by ijacquez** [comment]
I just retried the installer, and I can confirm that downloading the `.7z` took no more than a few seconds. Thank you @WinterMute.

**Comment by WinterMute** [comment]
> I just retried the installer, and I can confirm that downloading the `.7z` took no more than a few seconds. Thank you @WinterMute.

Awesome. Apologies for the inconvenience.
