### ISSUE TITLE
[bug] Not Installing Libraries After The App Itself Is Installed

### ISSUE THREAD

**Issue by githubissocool** [devkitPro/installer#43]
After I Installed devkitPro With 3DS Development, I Decided That I Want To Develop Nintendo Switch Homebrew Apps Too. But Whenever I Tick "Switch Development" When devkitPro Is Already Installed, It Doesn't Install The Required Libraries At All Such As libnx, This Goes Same For Ticking Other Development Options. So Please Fix This Because I Had To Uninstall devkitPro And Install It Again With Both 3DS And Switch Development Ticked.

**Comment by Elrinth** [comment]
for windows you can execute this to get the required libs to build the example programs:
"c:\devkitPro\msys2\usr\bin\pacman.exe" -S switch-portlib --noconfirm

**Comment by WinterMute** [comment]
Those tickboxes weren't really intended for this use case. Once you have the devkitPro msys2 bundle installed you can just use pacman directly to install anything you need. Just open the msys2 shell & run `pacman -S switch-dev` in your case.
