### ISSUE TITLE
failed retrieving file 'dkp-libs.db' from pkg.dekitpro.org

### ISSUE THREAD

**Issue by 8CBCA403** [devkitPro/installer#44]
![error](https://user-images.githubusercontent.com/99472048/166389940-84c5fac2-f5d7-461f-8cc4-1ea26d379b4b.png)

**Comment by Wanghaoran86** [comment]
also when i try to visit https://pkg.devkitpro.org/packages/windows/x86_64/$arch
![image](https://user-images.githubusercontent.com/99472048/166390031-0e9da3f3-77e7-41b7-8ad9-49f7251137d6.png)

**Comment by WinterMute** [comment]
Closing as old. If this is still a problem please open a new issue.
