### ISSUE TITLE
Installer does not download DevKitARM

### ISSUE THREAD

**Issue by ATSxp** [devkitPro/installer#45]
Hello, I'm a Windows 7 user, and I had installed DevKitARM on a machine a while ago (but I uninstalled it because I wasn't having fun =/ ) but today I went to install it and it just downloaded these folders:
![image](https://user-images.githubusercontent.com/92697714/189994847-318c6769-00b3-4fa1-b5d2-af0db92bb0be.png)

I know this problem is becoming common, and I have an idea that it is a server problem. Could you please help me to install it correctly?

Thank you for creating this project, I wish I could help by contributing something, but unfortunately I don't even have money for myself XD

**Comment by fincs** [comment]
You can open the msys2 shell and type `pacman -S <consolename>-dev` to get all the packages you need for developing homebrew for `<consolename>`. For example, `pacman -S gba-dev` gets you a working installation for GBA development.

**Comment by ATSxp** [comment]
> You can open the msys2 shell and type `pacman -S <consolename>-dev` to get all the packages you need for developing homebrew for `<consolename>`. For example, `pacman -S gba-dev` gets you a working installation for GBA development.

It may sound funny, but I found a guy with the same problem as me on the forum, and you were there and said the same thing, I did what you said and that's it, it's in my folder =).

Thank you so much for helping, I believe this should be written somewhere on the "Getting Started" page, as some Windows users (like me),
they would never know this if they opened an issue or searched very patiently on the internet.

Thank you anyway ;)

**Comment by fincs** [comment]
Glad you got it sorted out. Fwiw [the same instructions are already on the Getting Started page](https://devkitpro.org/wiki/Getting_Started#Unix-like_platforms).
