### ISSUE TITLE
error: <package>: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust

### ISSUE THREAD

**Issue by LOuroboros** [devkitPro/installer#46]
Hi.

When I type `pacman -S make gcc zlib-devel git` inside `C:\devkitPro\msys2\msys2_shell.bat`, I get roadblocked by these weird errors.

> (45/45) checking keys in keyring                             [###############################] 100%
> (45/45) checking package integrity                           [###############################] 100%
> error: perl-Clone: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
> :: File /var/cache/pacman/pkg/perl-Clone-0.45-2-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
> Do you want to delete it? [Y/n] y
> error: perl-IO-HTML: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
> :: File /var/cache/pacman/pkg/perl-IO-HTML-1.004-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
> Do you want to delete it? [Y/n] y
> error: perl-HTTP-Cookies: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
> :: File /var/cache/pacman/pkg/perl-HTTP-Cookies-6.10-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
> Do you want to delete it? [Y/n] y
> error: failed to commit transaction (invalid or corrupted package)
> Errors occurred, no packages were upgraded.

**Comment by LOuroboros** [comment]
Solved.

Running `pacman -S devkitpro-keyring` and then `pacman -S make gcc zlib-devel git` again was good enough.

Leaving this open until a mantainer comes along for visibility. It would be great if this wasn't a problem for users to deal with to begin with, or if at least the shell actually told the user about it.

**Comment by WinterMute** [comment]
> Solved.
> 
> Running `pacman -S devkitpro-keyring` and then `pacman -S make gcc zlib-devel git` again was good enough.
> 
> Leaving this open until a mantainer comes along for visibility. It would be great if this wasn't a problem for users to deal with to begin with, or if at least the shell actually told the user about it.

Deleting the packages was enough. That was an msys2 maintainer key and unaffected by devkitpro-keyring. 

These things are mainly a result of irregular updates. It's generally advised to install using -Sy to update databases.
