### ISSUE TITLE
Errors in MSYS

### ISSUE THREAD

**Issue by P0W3** [devkitPro/installer#47]
I used "pacman -Suy", and these are the errors that I have found. These are the same errors from devkitPro.

`:: Synchronizing package databases...
 msys is up to date
 dkp-libs.db failed to download
error: failed retrieving file 'msys.db' from downloads.sourceforge.net : error setting certificate verify locations:  CAfile: /usr/ssl/certs/ca-bundle.crt CApath: none
error: failed retrieving file 'msys.db' from www2.futureware.at : error setting certificate verify locations:  CAfile: /usr/ssl/certs/ca-bundle.crt CApath: none
error: failed retrieving file 'msys.db' from mirror.yandex.ru : error setting certificate verify locations:  CAfile: /usr/ssl/certs/ca-bundle.crt CApath: none
error: failed retrieving file 'msys.db' from mirrors.tuna.tsinghua.edu.cn : error setting certificate verify locations:  CAfile: /usr/ssl/certs/ca-bundle.crt CApath: none
error: failed retrieving file 'dkp-libs.db' from downloads.devkitpro.org : error setting certificate verify locations:  CAfile: /usr/ssl/certs/ca-bundle.crt CApath: none
error: failed to synchronize all databases (download library error)`

**Comment by WinterMute** [comment]
This kind of thing seems to be a hazard of not updating an msys2 install regularly.
