### ISSUE TITLE
devkitPro updater doesn't download any files (Win 11)

### ISSUE THREAD

**Issue by TechStudent10** [devkitPro/installer#48]
Similar to #11, on Windows 11 devkitPro only downloads `msys2`, the updater and the uninstaller. Enabling all SSL, TLS x.x in `inetcpl.cpl` does nothing. I don't live in the US so the Comcast thing doesn't apply to me. Instead the updater jumps to creating an uninstall file:

![image](https://user-images.githubusercontent.com/76978184/211126519-be1cd74d-7727-4631-a1f3-b8db79a37179.png)
> Window after it supposedly "downloaded" the files

It seems that devkitPro isn't in development anymore, which is a shame. I really wanted to get into 3DS homebrew, but until this is fixed, I can't

**Comment by pugsforlifebruh12** [comment]
Try running with Administrator perms

**Comment by WinterMute** [comment]
This can be an issue with our msys2 bundle needing updated. Can you try this again?

**Comment by WinterMute** [comment]
Testing shows this is fixed
