### ISSUE TITLE
devkitPro's fork of MSys2 lost access to packages such as build-essential

### ISSUE THREAD

**Issue by LOuroboros** [devkitPro/installer#49]
Title.

I installed the Windows version of devkitPro for reasons straight from the installer, booted up msys2_shell.bat, ran `pacman -Syu` and then proceeded to try to install certain packages via `pacman -S`, more specifically I used `pacman -S make git build-essentials libpng-devel pugixml pkg-config`.
The result?
> warning: make-4.4-1 is up to date -- reinstalling
> error: target not found: build-essentials
> error: target not found: libpng-devel
> error: target not found: pugixml
> warning: pkgconf-1.9.4-1 is up to date -- reinstalling

The warnings are whatever, but the packages that were available before and now are not available anymore are a tad concerning.

Were they renamed or something like that?

**EDIT**: Typing `build-essential` gives the same "target not found" error btw.

**Comment by WinterMute** [comment]
make, git and pkg-config are already installed in the devkitPro bundle we supply.

the rest aren't msys2 packages so I guess you're getting mixed up with something else.
