### ISSUE TITLE
default-arm7-0.7.3.tar.bz2 could not be downloaded at this time.

### ISSUE THREAD

**Issue by Diagamma** [devkitPro/installer#5]
Hi, this error message appears when I try to install devkitPro, I think it's because of f9f8484b87f21e2334b6b0b8c4bd54f180f3b572 but I don't know how to fix it. 
My guess is that it's something on the repo's side, so I don't really know what else to provide. 
Sorry if this isn't the right place to report it.

**Comment by Diagamma** [comment]
Apparently it's fixed.

**Comment by RafaelOliveira71594** [comment]
Why Did You Edit The Entire Issue . And Then Close It ?
