### ISSUE TITLE
3ds Makefile error

### ISSUE THREAD

**Issue by SkyplayYT** [devkitPro/installer#50]
I tried to make the 3dsx file, but it doesn't work. Here is the error:
![image-4.png](https://user-images.githubusercontent.com/103359249/223813200-14c3f5a1-0613-422c-8957-47aa22d95c5e.png)

I tried the same with Wii and other and it works, expect 3ds and Nds. Both have the same error. I am not sure if it is the insaller or I am to stupid to use it.

**Comment by WinterMute** [comment]
There was a hiccup with the devkitarm rules package causing issues on windows. Sorry for the inconvenience. Update your installation with pacman -Syu and the problem should be sorted.
