### ISSUE TITLE
Installer installs an old compiler 

### ISSUE THREAD

**Issue by ElezzarDev** [devkitPro/installer#52]
I was having some issues with compiling other peoples source code when someone told me to run
  `arm-eabi-gcc --version`

in my c:\devkitPro\devkitARM\bin directory from command line and it outputs this

`arm-eabi-gcc (devkitARM release 32) 4.5.1
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

from my understanding this is a very old compiler and i don't know why it keeps installing this version
I've also tried deleting the devkitPro directory and installing again from the latest release again and it still installs the same outdated compiler

any help on this would be greatly appreciated, thanks in advance!

**Comment by WinterMute** [comment]
The installer we supply does not install devkitARM release 32, a toolchain we released in 2010. As we said in https://devkitpro.org/viewtopic.php?t=9497 please use the uninstall option, download this installer https://github.com/devkitPro/installer/releases/tag/v3.0.3 and run it.

If that doesn't work then try formatting your hard drive, reinstalling windows and repeating the above steps.
