### ISSUE TITLE
Doesn't even work

### ISSUE THREAD

**Issue by LuaGunsX** [devkitPro/installer#53]
Every time I try to install, bash.exe doesn't work at all. It works half way through but it still doesn't work.

**Comment by WinterMute** [comment]
Will need a better description of the problem to help. What exactly is happening?

**Comment by LuaGunsX** [comment]
Whenever I try to install it at the bash.exe part, it automatically closes.

**Comment by WinterMute** [comment]
> Whenever I try to install it at the bash.exe part, it automatically closes.

I don't understand what you're saying here. What do you mean by "bash.exe part" and "automatically closes"?

**Comment by LuaGunsX** [comment]
Nevermind, just close this

**Comment by WinterMute** [comment]
If you have an issue we'd obviously like to help but there's only so much we can do if people can't describe the issue they're having. We know the installer works on most systems though.

**Comment by LuaGunsX** [comment]
I managed to figure out the issue; it turns out I didn't have msys2 (lmao).
