### ISSUE TITLE
Im having some issues with library's and their locations.

### ISSUE THREAD

**Issue by Grego-Watson** [devkitPro/installer#54]
Hi, I want to develop Wii Homebrew games using devkitpro and GRRLIB.
when i open up the example template in VSCode the include headers are all underlined red saying it can not find them, both grrlib.h and wiiuse.h. 

i tried installing libogc https://github.com/devkitPro/libogc but i had no luck not knowing what folder to put it in or if i need to do anything else.

I also followed the exact GRRlib instalation and devkitpro installation so im not sure whats wrong.
thanks in advance

**Comment by WinterMute** [comment]
This is the issue tracker for the installer, not a forum for questions about wii homebrew.  You can ask here https://devkitpro.org/viewforum.php?f=40 but we don't support grrlib, sorry.
