### ISSUE TITLE
devKitPro Installation breaks OpenSSH ssh-agent and ssh-add.

### ISSUE THREAD

**Issue by Kinokoda** [devkitPro/installer#55]
### What's the issue you encountered?

After Installing devKitPro for Switch development, my ssh-agent stopped working. 
### How can the issue be reproduced?

Installing/enabling the OpenSSH client on Windows 11 and then Installing devKitPro.

### Environment?

Using Windows 11 and I installed dvp with the GUI installer

### Additional context?

If any more info is required do reply/send me an email.
I simply wanted to note this down for the people that might need to know about it.
Have a good one and thank you for your work!

**Comment by WinterMute** [comment]
The msys2 environment supplies its own openssh client . This unfortunately is a major issue with using *nix tools on Windows and adding things to the path. For devkitPro tooling we had major issues with windows users not being able to use the tools without the msys2 binaries in the system path and being advised to do inappropriate things to "solve" the issue of not using the msys2 shell. The solution here is to use the msys2 ssh client instead or, if using the Microsoft OpenSSH feature, not to have the msys2 binaries in the system path at all.

The current installer needs replacing, it was written to manage binary distribution before we shifted to using pacman everywhere.
