### ISSUE TITLE
After installation 3.0.3, starting Msys2 prompts a message stating that the bash file is missing.

### ISSUE THREAD

**Issue by ZMYCat** [devkitPro/installer#56]
Bug Report
After installing devkitProUpdater-3.0.3.exe, when I try to launch Msys2 from the devkitPro directory, it shows a message that says "bash file not found." My computer doesn't have antivirus software installed, and Windows Security Center is already disabled. I've checked for any file interceptions, but found none.
![image](https://github.com/devkitPro/installer/assets/38978585/d2e3e4fd-cfaa-4183-b164-a0512df2cc21)

How can the issue be reproduced?
After running the installation file for version 3.0.3, attempting to launch the Msys2 included with devkitPro results in the mentioned error.

Environment?
Using Windows 11 22H2(22621.3007)
I have tried installing it on another computer as well as on a virtual machine running Windows 10, but the same issue persists when attempting to launch Msys2 included with devkitPro.

Additional context?
The downloaded version of Msys2 is msys-2.10.0.1.7z. I attempted to copy the bash.exe file from the compressed folder into the devkitPro's Mysys2/usr/bin/ directory. While Msys2 can now start, I still cannot utilize the devkitPro environment.

**Comment by cuibonobo** [comment]
Same issue. I also don't have interventions from my virus scanner. The `bash.exe` file seems to disappear in the middle of the install.

**Comment by DacoTaco** [comment]
quick question for @ZMYCat & @cuibonobo, what path was this installed to? i want to try and reproduce this in a VM
don't forget to censor user names in the path before posting etc so you don't dox yourself hehe

**Comment by ZMYCat** [comment]
> quick question for @ZMYCat & @cuibonobo, what path was this installed to? i want to try and reproduce this in a VM don't forget to censor user names in the path before posting etc so you don't dox yourself hehe



In my past few installations, I've used the default installation path provided by the installation software.
![image](https://github.com/devkitPro/installer/assets/38978585/0f3a7f67-a956-4b1a-96c0-e807eab05345)
: )

**Comment by DacoTaco** [comment]
okido! ill test this later on my W11 23H2 installation. it could have been that any space in the path could have resulted in some errors, but thats not the case !

**Comment by DacoTaco** [comment]
@ZMYCat : the issue has been resolved. please uninstall everything, delete any msys*.7z files you can find or have as the msys archive needed to be rebuild. it installed fine on my system after that!

thanks for reporting this, and please let us know if it now works to install :)

**Comment by WinterMute** [comment]
> My computer doesn't have antivirus software installed, and Windows Security Center is already disabled. 

This is a terrible idea, I really recommend at least having defender enabled although with scanning disabled for the devkitPro folder because it majorly impacts on compilation times.

It may also be worth rebooting after uninstalling & deleting files then making sure the devkitPro folder has been fully removed. Sometimes stray msys2 processes get left behind which prevent everything being removed properly.

**Comment by cuibonobo** [comment]
@DacoTaco Just confirmed that it works. Uninstalled devkitPro tools, rebooted, and reinstalled and now Msys2 is able to start up properly.

**Comment by Mariokid1234** [comment]
### i have the same issue
