### ISSUE TITLE
I'm blocked by devkitpro.org?

### ISSUE THREAD

**Issue by SquiddyGoat** [devkitPro/installer#57]
For some reason, Cloudflare blocked me from all devkitpro resources and forums. I can't access anything, and I cannot re-install devkitpro on my PC as my computer won't connect to their servers.

I would like to know what can be done about this, as I haven't posted anything on the site or done virtually anything besides create an account.

**Comment by dashaneryoutube** [comment]
Hey! I might know why this is happening. Cloudflare is a security program, so it might be blocking you for security reasons. If that is not the reason, you might not have a stable connection to the servers.


Hope this helps!

**Comment by dashaneryoutube** [comment]
Hey! I might know why this is happening. Cloudflare is a security program, so it might be blocking you for security reasons. If that is not the reason, you might not have a stable connection to the servers.


Hope this helps!

**Comment by dashaneryoutube** [comment]
> For some reason, Cloudflare blocked me from all devkitpro resources and forums. I can't access anything, and I cannot re-install devkitpro on my PC as my computer won't connect to their servers.
> 
> I would like to know what can be done about this, as I haven't posted anything on the site or done virtually anything besides create an account.

Hey! I might know why this is happening. Cloudflare is a security program, so it might be blocking you for security reasons. If that is not the reason, you might not have a stable connection to the servers.


Hope this helps!

**Comment by WinterMute** [comment]
If you're still blocked then pop an email to support@devkitpro.org with your IP address.
