### ISSUE TITLE
I can't install devkitPro

### ISSUE THREAD

**Issue by RainyRainbows** [devkitPro/installer#58]
i can't use DS Game Maker because the msys2 fails to download dlls and all that stuff, you know.
I am using Windows 11 Professional Edition and i have my antivirus disabled.

**Comment by ghost** [comment]
same, win11
![image](https://github.com/devkitPro/installer/assets/66655201/27ea5057-8c3e-4c5a-ae08-0fa293f729e4)

**Comment by WinterMute** [comment]
We don't support use of DS Game Maker, sorry.

**Comment by RainyRainbows** [comment]
> We don't support use of DS Game Maker, sorry.

but IT DOES
