### ISSUE TITLE
Doesn't Download any other developments.

### ISSUE THREAD

**Issue by bulkmoerls** [devkitPro/installer#59]
The Latest Version I am Installing is 3.0.3, but it only gave me msys2 and others. why?

**Comment by WinterMute** [comment]
The installer isn't currently sophisticated enough to know when msys2 needs a core update which quits early and then doesn't install the other tools. You can still usually open the msys2 shell and run updates manually then install tools from there. Really we should probably simplify the installer and document installing toolchains & libs from the shell but sadly many other things take up our time & we lack the requisite circular tuit.

We've updated the basic msys2 package again recently so others shouldn't encounter this now. You can either uninstall what you have now or open the msys2 shell (start->devkitPro->msys2) and run pacman -Syu then, if it does a core update and quits early, pacman -Su. After that you can then install one of the dev groups - see https://devkitpro.org/wiki/devkitPro_pacman#Predefined_Groups
