### ISSUE TITLE
[MAJOR] Failed msys2 installation empties "path" env variable.

### ISSUE THREAD

**Issue by mariohackandglitch** [devkitPro/installer#8]
Title describes the error pretty much. Trying to use the release 3.0.2 set my path env variable to an empty string. This is a major bug for obvius reasons, the user will have to manually add the path entries back.

How I got the error:

- Install devkitPro toolchains with the installer normally until it says "Completed!" without clicking next and leave it open.
- Uninstall devkitPro toolchains using the unistaller.
- Click next and finish in the still open Updater.
- Reinstall devkitPro toolchains.

(NOTE: I already had a msys2 installation in my computer, no idea if it has anything to do.)

Results:
https://cdn.discordapp.com/attachments/302856274872369152/452122656389726239/unknown.png
https://cdn.discordapp.com/attachments/302856274872369152/452123450111295489/unknown.png

**Comment by WinterMute** [comment]
Apologies. I have a fresh windows install and neglected to replace the standard NSIS compiler with the large strings version.

https://github.com/devkitPro/installer/releases/tag/v3.0.3 should fix this. I've also added checks to the uninstall section for attempts to write blank path.

**Comment by WinterMute** [comment]
Hopefully sorted.

![avast-whitelisted](https://user-images.githubusercontent.com/101194/41001190-30424c72-6908-11e8-8784-fffdfef9852f.png)

Did 3.0.3 sort your PATH issue ok?

**Comment by mariohackandglitch** [comment]
Yes, tried to reproduce the bug and it didn't happen again. Thanks!
