### ISSUE TITLE
License for installer

### ISSUE THREAD

**Issue by ijacquez** [devkitPro/installer#9]
I currently have a private fork of `devkitPro/installer`. I plan to make major changes to fit my own project.

Is there a particular license tied to this project?

**Comment by WinterMute** [comment]
Being honest if I was to do this over again I would probably use the [Qt Installer Framework](http://doc.qt.io/qtinstallerframework/) instead. The nsis script and plugins have been difficult to maintain, most especially the large strings build which I keep forgetting about when I set up on a new machine.

There are also a lot of false positives from virus scanners on the installer which I presume is some heuristic which is mis-categorising the download plugin. 

The normal [msys2](https://github.com/msys2/msys2-installer) installer is QtIFW based and might be better suited to your needs. msys2 also has a QtIFW package available.

**Comment by ijacquez** [comment]
Thanks for your input. I did run a few tests, and I experienced that very problem (flagged as a virus). I also experienced issues with `ExecWait` and error handling looks to be a pain.

I'll explore the QtIFW route. Thanks.
